#
# Makefile for UNIX (System V)
#

CFLAGS = -O -DUNIX

MACH=	unix.o

OBJ=	main.o edit.o linefunc.o normal.o cmdline.o charset.o \
	format_l.o misccmds.o help.o dec.o inc.o search.o alloc.o \
	mk.o regexp.o regsub.o version.o \
	s_io.o mark.o screen.o fileio.o param.o $(MACH)

all : stevie

stevie : $(OBJ)
	$(CC) $(OBJ) $(LIBS) -o stevie

clean :
	rm $(OBJ)
