#
# Makefile for the Atari ST - Megamax C compiler
#

CFLAGS = -DMEGAMAX

#	Megamax rule
.c.o:
	mmcc $(CFLAGS) $<
	mmimp $*.o
	mmlib rv vi.lib $*.o

MACH=	tos.o

OBJ=	main.o edit.o linefunc.o normal.o cmdline.o charset.o \
	format_l.o misccmds.o help.o dec.o inc.o search.o alloc.o \
	mk.o regexp.o regsub.o version.o \
	s_io.o mark.o screen.o fileio.o param.o $(MACH)

all : stevie.ttp

stevie.ttp : $(OBJ)
	$(LINKER) vi.lib $(LIBS) -o stevie.ttp

clean :
	$(RM) $(OBJ) vi.lib
